export const MAIN_MODEL_MESSAGE_LIMIT = 16;
export const SHORT_TERM_MEMORY_TURN_CAPACITY = Math.floor(MAIN_MODEL_MESSAGE_LIMIT / 2);
export const DEFAULT_LONG_TERM_MEMORY_UPDATE_INTERVAL_TURNS = SHORT_TERM_MEMORY_TURN_CAPACITY;
export const LONG_TERM_MEMORY_UPDATE_INTERVAL_MAX_TURNS = SHORT_TERM_MEMORY_TURN_CAPACITY;
